### ISSUE TITLE
Ensure properly typed json payloads

### ISSUE THREAD

**Issue by jsamoocha** [stravalib/stravalib#280]
Some endpoints (e.g., /activities/{id} with PUT method) expect a JSON payload with boolean parameters. These are now "serialized" in the client by converting them to 1/0 integer values. While these are accepted for now by Strava, "1" or "true" are not valid boolean literals in JSON.

The `requests` library now has a `json` kwarg that correctly serializes a python dict into JSON. As an alternative, the solution proposed in #248 may also help.

**Comment by lwasser** [comment]
@jsamoocha again i'm just cleaning things up. was this issue addressed with our pydantic migration? or do you want to keep it open? it's from november 2022 so it's been open for some time!

**Comment by jsamoocha** [comment]
This is not solved yet, as we don't use pydantic for creating requests.

**Comment by lwasser** [comment]
cool thanks. i see that now. i left a message in slack to get more info. what would it look like to convert to pydantic in this case? i'm interested in working on this to better contribute to the API. i've used pydantic but not to generate json / perform API calls. i know i could work on other infrastructure things but i've been looking for a smaller issue where i could actually work on the code a bit.

**Comment by Taur1ne** [comment]
Oh, I should’ve looked at the issues prior to creating my own. #716 is a duplicate of this and #718 may resolve the problem
